# GitHub Releaseを作成する
name: Create Release

on:
  workflow_call:
    inputs:
      git_version:
        description: 'Gitタグとしてのバージョン（edge または v{version}）'
        type: string
        required: true

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # リリースを作成
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.git_version }}
          commit: ${{ github.sha }}
          prerelease: true
          generateReleaseNotes: true
          allowUpdates: true
          omitNameDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          omitBodyDuringUpdate: true
