# PythonパッケージをPyPIにリリースする
name: Release PyPI

on:
  workflow_call:
    inputs:
      app_version:
        description: 'アプリケーションのバージョン（PEP 440）'
        type: string
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release-pypi:
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            os: 'ubuntu-22.04'
            sed: 'sed'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          enable-cache: true
          cache-suffix: ${{ runner.os }}

      - name: Install gsed for macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install gnu-sed

      - name: Replace Version
        run: |
          ${{ matrix.sed }} -i "s/__version__ = \"0.0.0\"/__version__ = \"${{ inputs.app_version }}\"/" aoirint_matvtool/__init__.py
          ${{ matrix.sed }} -i "s/version = \"0.0.0\"/version = \"${{ inputs.app_version }}\"/" pyproject.toml

      - name: Install Python Dependencies
        run: uv sync --all-groups

      - name: Build Package
        run: uv build

      # NOTE: PyPIでTrusted publisherとしてGitHubリポジトリの登録が必要
      - name: Publish Package
        run: uv publish --trusted-publishing always
